local inserted = false

function DBMCPHotS()
	if inserted then return end
	DBM:AddCountSound("HoTS: Default", "HoTS_Default", "Interface\\AddOns\\DBM-CountPack-HoTS\\Default\\", 5, true)
	DBM:AddCountSound("HoTS: Abathur", "HoTS_Abathur", "Interface\\AddOns\\DBM-CountPack-HoTS\\Abathur\\", 5, true)
	DBM:AddCountSound("HoTS: Adjutant", "HoTS_Adjutant", "Interface\\AddOns\\DBM-CountPack-HoTS\\Adjutant\\", 5, true)
	DBM:AddCountSound("HoTS: Alarak", "HoTS_Alarak", "Interface\\AddOns\\DBM-CountPack-HoTS\\Alarak\\", 5, true)
	DBM:AddCountSound("HoTS: Alexstrasza", "HoTS_Alexstrasza", "Interface\\AddOns\\DBM-CountPack-HoTS\\Alexstrasza\\", 5, true)
	DBM:AddCountSound("HoTS: Anduin", "HoTS_Anduin", "Interface\\AddOns\\DBM-CountPack-HoTS\\Anduin\\", 5, true)
	DBM:AddCountSound("HoTS: Angel", "HoTS_Angel", "Interface\\AddOns\\DBM-CountPack-HoTS\\Angel\\", 5, true)
	DBM:AddCountSound("HoTS: Anubarak", "HoTS_Anubarak", "Interface\\AddOns\\DBM-CountPack-HoTS\\Anubarak\\", 5, true)
	DBM:AddCountSound("HoTS: Arena", "HoTS_Arena", "Interface\\AddOns\\DBM-CountPack-HoTS\\Arena\\", 5, true)
	DBM:AddCountSound("HoTS: Arthas", "HoTS_Arthas", "Interface\\AddOns\\DBM-CountPack-HoTS\\Arthas\\", 5, true)
	DBM:AddCountSound("HoTS: Athena", "HoTS_Athena", "Interface\\AddOns\\DBM-CountPack-HoTS\\Athena\\", 5, true)
	DBM:AddCountSound("HoTS: Barbarian", "HoTS_Barbarian", "Interface\\AddOns\\DBM-CountPack-HoTS\\Barbarian\\", 5, true)
	DBM:AddCountSound("HoTS: Blackheart", "HoTS_Blackheart", "Interface\\AddOns\\DBM-CountPack-HoTS\\Blackheart\\", 5, true)
	DBM:AddCountSound("HoTS: Blaze", "HoTS_Blaze", "Interface\\AddOns\\DBM-CountPack-HoTS\\Blaze\\", 5, true)
	DBM:AddCountSound("HoTS: Brightwing", "HoTS_Brightwing", "Interface\\AddOns\\DBM-CountPack-HoTS\\Brightwing\\", 5, true)
	DBM:AddCountSound("HoTS: Cloaken", "HoTS_Cloaken", "Interface\\AddOns\\DBM-CountPack-HoTS\\Cloaken\\", 5, true)
	DBM:AddCountSound("HoTS: Commodore", "HoTS_Commodore", "Interface\\AddOns\\DBM-CountPack-HoTS\\Commodore\\", 5, true)
	DBM:AddCountSound("HoTS: Crusader", "HoTS_Crusader", "Interface\\AddOns\\DBM-CountPack-HoTS\\Crusader\\", 5, true)
	DBM:AddCountSound("HoTS: Deathwing", "HoTS_Deathwing", "Interface\\AddOns\\DBM-CountPack-HoTS\\Deathwing\\", 5, true)
	DBM:AddCountSound("HoTS: Deckard Cain", "HoTS_Deckard", "Interface\\AddOns\\DBM-CountPack-HoTS\\Deckard\\", 5, true)
	DBM:AddCountSound("HoTS: Demon", "HoTS_Demon", "Interface\\AddOns\\DBM-CountPack-HoTS\\Demon\\", 5, true)
	DBM:AddCountSound("HoTS: Valla", "HoTS_DemonHunter", "Interface\\AddOns\\DBM-CountPack-HoTS\\DemonHunter\\", 5, true)
	DBM:AddCountSound("HoTS: Diablo", "HoTS_Diablo", "Interface\\AddOns\\DBM-CountPack-HoTS\\Diablo\\", 5, true)
	DBM:AddCountSound("HoTS: Drek'Thar", "HoTS_Drekthar", "Interface\\AddOns\\DBM-CountPack-HoTS\\Drekthar\\", 5, true)
	DBM:AddCountSound("HoTS: D.Va", "HoTS_Dva", "Interface\\AddOns\\DBM-CountPack-HoTS\\Dva\\", 5, true)
	DBM:AddCountSound("HoTS: E.T.C.", "HoTS_ETC", "Interface\\AddOns\\DBM-CountPack-HoTS\\ETC\\", 5, true)
	DBM:AddCountSound("HoTS: Falstad", "HoTS_Falstad", "Interface\\AddOns\\DBM-CountPack-HoTS\\Falstad\\", 5, true)
	DBM:AddCountSound("HoTS: Fenix", "HoTS_Fenix", "Interface\\AddOns\\DBM-CountPack-HoTS\\Fenix\\", 5, true)
	DBM:AddCountSound("HoTS: Gardens", "HoTS_Gardens", "Interface\\AddOns\\DBM-CountPack-HoTS\\Gardens\\", 5, true)
	DBM:AddCountSound("HoTS: Garrosh", "HoTS_Garrosh", "Interface\\AddOns\\DBM-CountPack-HoTS\\Garrosh\\", 5, true)
	DBM:AddCountSound("HoTS: Gazlowe", "HoTS_Gazlowe", "Interface\\AddOns\\DBM-CountPack-HoTS\\Gazlowe\\", 5, true)
	DBM:AddCountSound("HoTS: Genji (JP)", "HoTS_Genji", "Interface\\AddOns\\DBM-CountPack-HoTS\\Genji\\", 5, true)
	DBM:AddCountSound("HoTS: Hanzo", "HoTS_Hanzo", "Interface\\AddOns\\DBM-CountPack-HoTS\\Hanzo\\", 5, true)
	DBM:AddCountSound("HoTS: Hogger", "HoTS_Hogger", "Interface\\AddOns\\DBM-CountPack-HoTS\\Hogger\\", 5, true)
	DBM:AddCountSound("HoTS: Illidan", "HoTS_Illidan", "Interface\\AddOns\\DBM-CountPack-HoTS\\Illidan\\", 5, true)
	DBM:AddCountSound("HoTS: Imperius", "HoTS_Imperoius", "Interface\\AddOns\\DBM-CountPack-HoTS\\Imperius\\", 5, true)
	DBM:AddCountSound("HoTS: Jaina", "HoTS_Jaina", "Interface\\AddOns\\DBM-CountPack-HoTS\\Jaina\\", 5, true)
	DBM:AddCountSound("HoTS: Junkrat", "HoTS_Junkrat", "Interface\\AddOns\\DBM-CountPack-HoTS\\Junkrat\\", 5, true)
	DBM:AddCountSound("HoTS: Junkrat (Alt)", "HoTS_JunkratAlt", "Interface\\AddOns\\DBM-CountPack-HoTS\\JunkratAlt\\", 5, true)
	DBM:AddCountSound("HoTS: Kel'Thuzad", "HoTS_KelThuzad", "Interface\\AddOns\\DBM-CountPack-HoTS\\KelThuzad\\", 5, true)
	DBM:AddCountSound("HoTS: Lady of Thorns", "HoTS_Thorns", "Interface\\AddOns\\DBM-CountPack-HoTS\\LadyOfThorns\\", 5, true)
	DBM:AddCountSound("HoTS: LiLi", "HoTS_LiLi", "Interface\\AddOns\\DBM-CountPack-HoTS\\LiLi\\", 5, true)
	DBM:AddCountSound("HoTS: Luncha", "HoTS_Luncha", "Interface\\AddOns\\DBM-CountPack-HoTS\\Luncha\\", 5, true)
	DBM:AddCountSound("HoTS: Maiev", "HoTS_Maiev", "Interface\\AddOns\\DBM-CountPack-HoTS\\Maiev\\", 5, true)
	DBM:AddCountSound("HoTS: Malfurion", "HoTS_Malfurion", "Interface\\AddOns\\DBM-CountPack-HoTS\\Malfurion\\", 5, true)
	DBM:AddCountSound("HoTS: Mal'Ganis", "HoTS_MalGanis", "Interface\\AddOns\\DBM-CountPack-HoTS\\MalGanis\\", 5, true)
	DBM:AddCountSound("HoTS: Mei", "HoTS_Mei", "Interface\\AddOns\\DBM-CountPack-HoTS\\Mei\\", 5, true)
	DBM:AddCountSound("HoTS: Mephisto", "HoTS_Mephisto", "Interface\\AddOns\\DBM-CountPack-HoTS\\Mephisto\\", 5, true)
	DBM:AddCountSound("HoTS: Metzen", "HoTS_Metzen", "Interface\\AddOns\\DBM-CountPack-HoTS\\Metzen\\", 5, true)
	DBM:AddCountSound("HoTS: Mira", "HoTS_Mira", "Interface\\AddOns\\DBM-CountPack-HoTS\\Mira\\", 5, true)
	DBM:AddCountSound("HoTS: Muradin", "HoTS_Muradin", "Interface\\AddOns\\DBM-CountPack-HoTS\\Muradin\\", 5, true)
	DBM:AddCountSound("HoTS: Murky", "HoTS_Murky", "Interface\\AddOns\\DBM-CountPack-HoTS\\Murky\\", 5, true)
	DBM:AddCountSound("HoTS: Necromancer", "HoTS_Necro", "Interface\\AddOns\\DBM-CountPack-HoTS\\Necromancer\\", 5, true)
	DBM:AddCountSound("HoTS: Qhira", "HoTS_NexusHunter", "Interface\\AddOns\\DBM-CountPack-HoTS\\NexusHunter\\", 5, true)
	DBM:AddCountSound("HoTS: Orphea", "HoTS_Orphea", "Interface\\AddOns\\DBM-CountPack-HoTS\\Orphea\\", 5, true)
	DBM:AddCountSound("HoTS: Ravenlord", "HoTS_Ravenlord", "Interface\\AddOns\\DBM-CountPack-HoTS\\RavenLord\\", 5, true)
	DBM:AddCountSound("HoTS: Rehgar", "HoTS_Rehgar", "Interface\\AddOns\\DBM-CountPack-HoTS\\Rehgar\\", 5, true)
	DBM:AddCountSound("HoTS: Summer Games (ES)", "HoTS_RingAnnouncer", "Interface\\AddOns\\DBM-CountPack-HoTS\\RingAnnouncer\\", 5, true)
	DBM:AddCountSound("HoTS: Sgt. Hammer", "HoTS_SiegeTank", "Interface\\AddOns\\DBM-CountPack-HoTS\\SiegeTank\\", 5, true)
	DBM:AddCountSound("HoTS: Snake God", "HoTS_Snake", "Interface\\AddOns\\DBM-CountPack-HoTS\\Snake\\", 5, true)
	DBM:AddCountSound("HoTS: Spider Queen", "HoTS_SpiderQueen", "Interface\\AddOns\\DBM-CountPack-HoTS\\SpiderQueen\\", 5, true)
	DBM:AddCountSound("HoTS: Stitches", "HoTS_Stitches", "Interface\\AddOns\\DBM-CountPack-HoTS\\Stitches\\", 5, true)
	DBM:AddCountSound("HoTS: Summer Games", "HoTS_Summer20", "Interface\\AddOns\\DBM-CountPack-HoTS\\Summer20\\", 5, true)
	DBM:AddCountSound("HoTS: Tassadar", "HoTS_Tassadar", "Interface\\AddOns\\DBM-CountPack-HoTS\\Tassadar\\", 5, true)
	DBM:AddCountSound("HoTS: The Kid", "HoTS_Toy18", "Interface\\AddOns\\DBM-CountPack-HoTS\\Toy18\\", 5, true)
	DBM:AddCountSound("HoTS: Toy Stitches", "HoTS_ToyStitches", "Interface\\AddOns\\DBM-CountPack-HoTS\\ToyStitches\\", 5, true)
	DBM:AddCountSound("HoTS: Tychus", "HoTS_Tychus", "Interface\\AddOns\\DBM-CountPack-HoTS\\Tychus\\", 5, true)
	DBM:AddCountSound("HoTS: Tyrael", "HoTS_Tyrael", "Interface\\AddOns\\DBM-CountPack-HoTS\\Tyrael\\", 5, true)
	DBM:AddCountSound("HoTS: Tyrael Mecha", "HoTS_TyraelMecha", "Interface\\AddOns\\DBM-CountPack-HoTS\\TyraelMecha\\", 5, true)
	DBM:AddCountSound("HoTS: Vanndar", "HoTS_Vanndar", "Interface\\AddOns\\DBM-CountPack-HoTS\\Vanndar\\", 5, true)
	DBM:AddCountSound("HoTS: Volskaya", "HoTS_Volskaya", "Interface\\AddOns\\DBM-CountPack-HoTS\\Volskaya\\", 5, true)
	DBM:AddCountSound("HoTS: Whitemane", "HoTS_Whitemane", "Interface\\AddOns\\DBM-CountPack-HoTS\\Whitemane\\", 5, true)
	DBM:AddCountSound("HoTS: Nazeebo", "HoTS_WitchDoctor", "Interface\\AddOns\\DBM-CountPack-HoTS\\WitchDoctor\\", 5, true)
	DBM:AddCountSound("HoTS: Yrel", "HoTS_Yrel", "Interface\\AddOns\\DBM-CountPack-HoTS\\Yrel\\", 5, true)
	DBM:AddCountSound("HoTS: Zeratul", "HoTS_Zeratul", "Interface\\AddOns\\DBM-CountPack-HoTS\\Zeratul\\", 5, true)
	inserted = true
end
